

from LC1_DEFS import * 



USE_SESSION_VIEW = True 

N_TRACKS = 4 
N_SCENES = 5 


TRACK_CLIP_BUTTONS = [32, 36, 40, 44, 48, 33, 37, 41, 45, 49, 34, 38, 42, 46, 50, 35, 39, 43, 47, 51] # Must be N_TRACKS x N_SCENES in length
ENCODER_DIALS = [16, 17, 18, 19, 20, 21, 22, 23]

CLIP_STARTED_COLOR = C_GREEN 
CLIP_STOP_COLOR = C_BLUE 
CLIP_TRG_PLAY_COLOR = C_PINK 
NO_CLIP_COLOR = C_OFF


USE_SESSION_NAV = True 
NAVBOX_LEFT_BUTTON = 58
NAVBOX_LEFT_BUTTON_C = C_BLUE
NAVBOX_RIGHT_BUTTON = 59
NAVBOX_RIGHT_BUTTON_C = C_PINK
NAVBOX_UP_BUTTON = 56
NAVBOX_UP_BUTTON_C = C_BLUE
NAVBOX_DOWN_BUTTON = 57
NAVBOX_DOWN_BUTTON_C = C_PINK

ZOOM_STOPPED = C_PINK
ZOOM_PLAYING = C_GREEN
ZOOM_SELECTED = C_BLUE

USE_MIXER_CONTROLS = True

USE_SENDS = False
#N_SENDS_PER_TRACK = 3 # sends per track
#SEND_ENCODERS = [1,2,3,9,10,11,17,18,19,25,26,27] 

USE_MIXER_EQ = False
USE_MIXER_FILTERS = False

USE_STOP_BUTTONS = True
STOP_BUTTONS = [52, 53, 54, 55] 
STOP_BUTTON_ON_COLOR = C_GREEN
STOP_BUTTON_OFF_COLOR = C_AMBER

USE_SELECT_BUTTONS = True
SELECT_BUTTONS = [20, 21, 22, 23] 
SELECT_BUTTON_ON_COLOR = C_GREEN
SELECT_BUTTON_OFF_COLOR = C_AMBER

USE_DEVICE_NAV_BUTTONS = True
DEVICE_NAV_BUTTONS = [16, 17, 18, 19]

USE_MUTE_BUTTONS = True
MUTE_BUTTONS = [64, 65, 66, 67] 
MUTE_BUTTON_ON_COLOR = C_GREEN
MUTE_BUTTON_OFF_COLOR = C_AMBER

USE_ARM_BUTTONS = True
ARM_BUTTONS = [72, 73, 74, 75] 
ARM_BUTTON_ON_COLOR = C_GREEN
ARM_BUTTON_OFF_COLOR = C_AMBER

USE_SOLO_BUTTONS = True
SOLO_BUTTONS = [68, 69, 70, 71]
SOLO_BUTTON_ON_COLOR = C_GREEN
SOLO_BUTTON_OFF_COLOR = C_AMBER

# VOLUME_ENCODERS can be any length <= N_TRACKS
USE_VOLUME_CONTROLS = False
#VOLUME_ENCODERS = [4,12,20,28]
############################

